services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../Docker/dockerfile.frontend
      args:
      - .dockerignore=../Docker/.dockerignore
    ports:
      - "801:80"
    volumes:
      - ./frontend:/app
    env_file:
      - ../frontend/.env
    depends_on:
      - backend
  backend:
    build:
      context: ../backend
      dockerfile: ../Docker/dockerfile.backend
      args:
      - .dockerignore=../Docker/.dockerignore
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ../backend/.env
    depends_on:
      - email_server
  email_server:
    build:
      context: ../email-server
      dockerfile: ../Docker/dockerfile.email
      args:
      - .dockerignore=../Docker/.dockerignore
    ports:
      - "8885:8885"
    volumes:
      - ./email_server:/app
    env_file:
      - ../email-server/.env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"


